# Generated by Django 3.2 on 2025-06-11 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pemesanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pelanggan', models.CharField(blank=True, max_length=100)),
                ('nomor_meja', models.CharField(max_length=10)),
                ('tanggal_pesan', models.DateTimeField(auto_now_add=True)),
                ('sudah_dibayar', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ItemPesanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.PositiveIntegerField()),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.menubakso')),
                ('pemesanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_pesanan', to='menu.pemesanan')),
            ],
        ),
    ]
