# Generated by Django 3.2 on 2025-06-12 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_itempesanan_pemesanan'),
    ]

    operations = [
        migrations.AddField(
            model_name='pemesanan',
            name='keterangan_pesanan',
            field=models.TextField(blank=True, null=True),
        ),
    ]
