# Generated by Django 3.2 on 2025-06-12 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_pemesanan_keterangan_pesanan'),
    ]

    operations = [
        migrations.AddField(
            model_name='pemesanan',
            name='jumlah_item',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pemesanan',
            name='status',
            field=models.CharField(choices=[('proses', 'Diproses'), ('selesai', 'Selesai')], default='proses', max_length=20),
        ),
    ]
