# Generated by Django 3.2 on 2025-06-13 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20250612_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menubakso',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
