# Generated by Django 3.2 on 2025-06-13 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_menubakso_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempesanan',
            name='pemesanan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu.pemesanan'),
        ),
    ]
